title: LinkThings Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://linkthingsstatus.netlify.com/'
params:
  disableDarkMode: false
  shortDateFormat: '15:04 — Jan 2'
  down: '#D11B1A'
  systems:
    - name: Power BI
      category: Power BI Portal
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#10325a'
  headerTextColor: white
  logo: /img/linkthings_logo_with_text.svg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#f7ca18'
  notice: '#24478f'
  incidentHistoryFormat: none
  ok: '#2ecc71'
  categories:
    - name: Power BI Portal
      closed: true
      untited: false
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
